### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by snashraf** [brentp/peddy#18]
Hi I was trying to run PEDDY on family cohorts. 
Here is PED file for family.

```
[nsyed@hpclogin1 PMC01]$ head PMC01.ped
PMC01   AB082422_S5_L005    ABM090010_S7_L007   ABC09005_S2_L002    1   -9          
PMC01   ABC09005_S2_L002    0   0   2   -9
PMC01   ABM090010_S7_L007   0   0   1   -9
[nsyed@hpclogin1 PMC01]$ zgrep  -m1 "#CHROM" ../../PMC/PMC01/PMC01.vcf.gz
#CHROM  POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  AB082422_S5_L005    ABC09005_S2_L002    ABM090010_S7_L007
```

And this is command that I have used. 
python -m peddy -p 12 --plot --prefix PMC01 ../../PMC/PMC01/PMC01.vcf.gz PMC01.ped

And below is the error.

```
[nsyed@hpclogin1 PMC01]$ python -m peddy -p 12 --plot ../../PMC/PMC01/PMC01.vcf.gz PMC01.ped
Traceback (most recent call last):
  File "/gpfs/software/tools/python2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/gpfs/software/tools/python2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/gpfs/software/tools/python2.7/lib/python2.7/site-packages/peddy-0.2.7-py2.7.egg/peddy/__main__.py", line 203, in <module>
    main(a.vcf, a.ped, prefix, a.plot, a.each, a.procs, a.sites)
  File "/gpfs/software/tools/python2.7/lib/python2.7/site-packages/peddy-0.2.7-py2.7.egg/peddy/__main__.py", line 121, in main
    sep="\t")
  File "/gpfs/software/tools/python2.7/lib/python2.7/site-packages/pandas/io/parsers.py", line 562, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/gpfs/software/tools/python2.7/lib/python2.7/site-packages/pandas/io/parsers.py", line 325, in _read
    return parser.read()
  File "/gpfs/software/tools/python2.7/lib/python2.7/site-packages/pandas/io/parsers.py", line 815, in read
    ret = self._engine.read(nrows)
  File "/gpfs/software/tools/python2.7/lib/python2.7/site-packages/pandas/io/parsers.py", line 1314, in read
    data = self._reader.read(nrows)
  File "pandas/parser.pyx", line 805, in pandas.parser.TextReader.read (pandas/parser.c:8748)
  File "pandas/parser.pyx", line 827, in pandas.parser.TextReader._read_low_memory (pandas/parser.c:9003)
  File "pandas/parser.pyx", line 904, in pandas.parser.TextReader._read_rows (pandas/parser.c:10022)
  File "pandas/parser.pyx", line 985, in pandas.parser.TextReader._convert_column_data (pandas/parser.c:11060)
  File "pandas/parser.pyx", line 1246, in pandas.parser.TextReader._get_column_name (pandas/parser.c:15064)
IndexError: list index out of range
```

**Comment by brentp** [comment]
Is your ped file tab separated? If not, I'd try that first. If that fixes it, let me know and I'll give a better error message.

**Comment by snashraf** [comment]
Yes, I was able to run this now. Their was some extra tab after last colums in first line . but now after running , I am getting another error.

[nsyed@hpclogin1 PMC01]$ python -m peddy -p 12 --plot --prefix PMC01 ../../PMC/PMC01/PMC01.vcf.gz PMC01.ped
ped_check
plotting
Traceback (most recent call last):
  File "/gpfs/software/tools/python2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/gpfs/software/tools/python2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/gpfs/software/tools/python2.7/lib/python2.7/site-packages/peddy-0.2.7-py2.7.egg/peddy/__main__.py", line 203, in <module>
    main(a.vcf, a.ped, prefix, a.plot, a.each, a.procs, a.sites)
  File "/gpfs/software/tools/python2.7/lib/python2.7/site-packages/peddy-0.2.7-py2.7.egg/peddy/__main__.py", line 152, in main
    in ("ped_check", "het_check", "sex_check")]):
  File "/gpfs/software/tools/python2.7/lib/python2.7/site-packages/peddy-0.2.7-py2.7.egg/peddy/__main__.py", line 31, in run
    prefix=prefix, **kwargs)
  File "/gpfs/software/tools/python2.7/lib/python2.7/site-packages/peddy-0.2.7-py2.7.egg/peddy/peddy.py", line 1072, in ped_check
    label="ped coef: %s" % src)
  File "/gpfs/software/tools/python2.7/lib/python2.7/site-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg/matplotlib/axes/_axes.py", line 3648, in scatter
    collection.set_alpha(alpha)
  File "/gpfs/software/tools/python2.7/lib/python2.7/site-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg/matplotlib/collections.py", line 650, in set_alpha
    if self._edgecolors_original != str('face'):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by brentp** [comment]
can you update matplotlib to the current version and let me know if you still see this issue?

**Comment by snashraf** [comment]
Since we build peddy from Github so matplotlib-1.4.3 version is included wihin. I made another installation using Anoconda and its working now.  You may close this now. Thanks for help again.

**Comment by brentp** [comment]
OK. Thanks for reporting back. I'll add matplotlib>=1.5.0 to the requirements. I'll keep this open til I make that change.

**Comment by brentp** [comment]
>1.5.0 is now in the reqs.
