### ISSUE TITLE
pip install fails to find `__version__` string

### ISSUE THREAD

**Issue by mdshw5** [brentp/peddy#2]
```
-bash-4.1$ pip3 install peddy
You are using pip version 7.0.3, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting peddy
  Downloading peddy-0.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-z_azrrhl/peddy/setup.py", line 20, in <module>
        setup(version=get_version(),
      File "/tmp/pip-build-z_azrrhl/peddy/setup.py", line 9, in get_version
        with open(os.path.join("peddy", "__init__.py"), "r") as init_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'peddy/__init__.py'
```
It looks like this method of parsing the version string is not working when installing the PyPI version. Installing from a tarball worked fine for me.

**Comment by brentp** [comment]
could you try again? I was able to reproduce, but I pushed a new version (no code changes; 0.0.2) and updated my pip and was able to get it to install.

**Comment by mdshw5** [comment]
```
-bash-4.1$ pip3 install peddy --user --upgrade
You are using pip version 7.0.3, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting peddy
  Downloading peddy-0.0.2.tar.gz
Building wheels for collected packages: peddy
  Running setup.py bdist_wheel for peddy
  Stored in directory: /home/shirlma2/.cache/pip/wheels/c9/15/5a/642391a771c109db73196d9cdb2ed91f12131e0d5ae9038085
Successfully built peddy
Installing collected packages: peddy
  Found existing installation: peddy 0.0.1
    Uninstalling peddy-0.0.1:
      Successfully uninstalled peddy-0.0.1
Successfully installed peddy-0.0.1
```

Looks like it's fixed. Thanks! I really like the idea of this package, and am starting to use it a bit - so if you have any outstanding improvements feel free to assign them to me in issues.

**Comment by brentp** [comment]
great! it's weird that it downloaded 0.0.2 and installed 0.0.1 ...

still figuring out what the rest of the API will look like but let me know any missing features.
