### ISSUE TITLE
Python/CyVCF2 error: "ZeroDivisionError: float division"

### ISSUE THREAD

**Issue by robinandeer** [brentp/peddy#23]
Hej @brentp!

I tried running peddy installed using conda on a standard VCF from our pipeline (GATK+Samtools+Freebayes) and seeing this error:

```bash
python -m peddy --plot --prefix cust002-F0009251 /mnt/hds/proj/bioinfo/SERVER/apps/housekeeper/analyses/cust002-F0009251/2017-03-14/F0009251_sorted_md_brecal_comb_vep_parsed_ranked_SV.vcf.gz /mnt/hds/proj/bioinfo/SERVER/apps/housekeeper/analyses/cust002-F0009251/2017-03-14/F0009251.fam
```

```python
no intervals found for /mnt/hds/proj/bioinfo/SERVER/apps/housekeeper/analyses/cust002-F0009251/2017-03-14/F0009251_sorted_md_brecal_comb_vep_parsed_ranked_SV.vcf.gz at 18:74402404-74402404
no intervals found for /mnt/hds/proj/bioinfo/SERVER/apps/housekeeper/analyses/cust002-F0009251/2017-03-14/F0009251_sorted_md_brecal_comb_vep_parsed_ranked_SV.vcf.gz at 18:74671768-74671768
no intervals found for /mnt/hds/proj/bioinfo/SERVER/apps/housekeeper/analyses/cust002-F0009251/2017-03-14/F0009251_sorted_md_brecal_comb_vep_parsed_ranked_SV.vcf.gz at 18:74692336-74692336
no intervals found for /mnt/hds/proj/bioinfo/SERVER/apps/housekeeper/analyses/cust002-F0009251/2017-03-14/F0009251_sorted_md_brecal_comb_vep_parsed_ranked_SV.vcf.gz at 18:74962645-74962645
no intervals found for /mnt/hds/proj/bioinfo/SERVER/apps/housekeeper/analyses/cust002-F0009251/2017-03-14/F0009251_sorted_md_brecal_comb_vep_parsed_ranked_SV.vcf.gz at 18:76754871-76754871
no intervals found for /mnt/hds/proj/bioinfo/SERVER/apps/housekeeper/analyses/cust002-F0009251/2017-03-14/F0009251_sorted_md_brecal_comb_vep_parsed_ranked_SV.vcf.gz at 18:77137202-77137202
no intervals found for /mnt/hds/proj/bioinfo/SERVER/apps/housekeeper/analyses/cust002-F0009251/2017-03-14/F0009251_sorted_md_brecal_comb_vep_parsed_ranked_SV.vcf.gz at 18:77473086-77473086
no intervals found for /mnt/hds/proj/bioinfo/SERVER/apps/housekeeper/analyses/cust002-F0009251/2017-03-14/F0009251_sorted_md_brecal_comb_vep_parsed_ranked_SV.vcf.gz at 18:77703476-77703476
no intervals found for /mnt/hds/proj/bioinfo/SERVER/apps/housekeeper/analyses/cust002-F0009251/2017-03-14/F0009251_sorted_md_brecal_comb_vep_parsed_ranked_SV.vcf.gz at 18:77893683-77893683
Traceback (most recent call last):
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/stage/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/stage/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/stage/lib/python2.7/site-packages/peddy/__main__.py", line 222, in <module>
    main(a.vcf, a.ped, prefix, a.plot, a.each, a.procs, a.sites)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/stage/lib/python2.7/site-packages/peddy/__main__.py", line 153, in main
    in ("ped_check", "het_check", "sex_check")]):
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/stage/lib/python2.7/site-packages/peddy/__main__.py", line 32, in run
    prefix=prefix, **kwargs)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/stage/lib/python2.7/site-packages/peddy/peddy.py", line 955, in ped_check
    min_depth=min_depth, each=each)
  File "cyvcf2/cyvcf2.pyx", line 50, in cyvcf2.cyvcf2.par_relatedness (cyvcf2/cyvcf2.c:4342)
  File "cyvcf2/cyvcf2.pyx", line 824, in cyvcf2.cyvcf2.VCF._relatedness_finish (cyvcf2/cyvcf2.c:20634)
ZeroDivisionError: float division
```

Maybe you recognize something or can point us to what we can try to narrow down what the cause is?

**Comment by brentp** [comment]
it seems like maybe you have no HET calls in the sites that peddy checks in one of your samples.

I'll add a check for this in peddy, but you probably have something with at least 1 sample.

**Comment by brentp** [comment]
I pushed a change to cyvcf2 that will inform which sample had no hets and try to avoid the error you saw. Could you install `cyvcf2` from github and let me know how it goes?

**Comment by robinandeer** [comment]
Thank you - you are very quick!

Now peddy runs! I do run into a different error tho - sry 😅  (I don't mean for you to fix it on a Friday afternoon hehe)

STDOUT:

```bash
ped_check
plotting
ran in 2.4 seconds
het_check
```

STDERR:

```python
no intervals found for /mnt/hds/proj/bioinfo/SERVER/apps/housekeeper/analyses/cust002-F0009251/2017-03-14/F0009251_sorted_md_brecal_comb_vep_parsed_ranked_SV.vcf.gz at 18:77137202-77137202
no intervals found for /mnt/hds/proj/bioinfo/SERVER/apps/housekeeper/analyses/cust002-F0009251/2017-03-14/F0009251_sorted_md_brecal_comb_vep_parsed_ranked_SV.vcf.gz at 18:77473086-77473086
no intervals found for /mnt/hds/proj/bioinfo/SERVER/apps/housekeeper/analyses/cust002-F0009251/2017-03-14/F0009251_sorted_md_brecal_comb_vep_parsed_ranked_SV.vcf.gz at 18:77703476-77703476
no intervals found for /mnt/hds/proj/bioinfo/SERVER/apps/housekeeper/analyses/cust002-F0009251/2017-03-14/F0009251_sorted_md_brecal_comb_vep_parsed_ranked_SV.vcf.gz at 18:77893683-77893683
Traceback (most recent call last):
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/stage/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/stage/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/stage/lib/python2.7/site-packages/peddy/__main__.py", line 222, in <module>
    main(a.vcf, a.ped, prefix, a.plot, a.each, a.procs, a.sites)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/stage/lib/python2.7/site-packages/peddy/__main__.py", line 153, in main
    in ("ped_check", "het_check", "sex_check")]):
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/stage/lib/python2.7/site-packages/peddy/__main__.py", line 32, in run
    prefix=prefix, **kwargs)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/stage/lib/python2.7/site-packages/peddy/peddy.py", line 848, in het_check
    sites, min_depth=min_depth)
  File "cyvcf2/cyvcf2.pyx", line 77, in cyvcf2.cyvcf2.par_het (cyvcf2/cyvcf2.c:5452)
  File "cyvcf2/cyvcf2.pyx", line 696, in cyvcf2.cyvcf2.VCF._finish_het (cyvcf2/cyvcf2.c:17596)
IndexError: index 0 is out of bounds for axis 0 with size 0
```

(I guess the "no intervals found" aren't an issue, right?)

**Comment by brentp** [comment]
No problem. I suspect something's odd about your data, but it would be good if the error message was informative.
is this a targetted sequencing project? it seems like you're getting 0 het calls. somehow.

you didn't see an error message about a sample with 0 het calls?

**Comment by robinandeer** [comment]
No I didn't

But you're right - this is a trio sequencing using the "focused exome" kit so it's targeting about 3000 genes if I remember correctly. Should I skip running peddy for targeted sequencing projects?

I just ran peddy on a WGS single sample analysis and it worked without errors!

I will test on a WGS trio but our cluster is a bit slow at the moment hehe

**Comment by brentp** [comment]
yeah, I would skip for targetted. I'm surprised it didn't get anything in 3K genes though. It's sampling ~25K sites from the exome so it seems like it should hit some 

If you could share the VCF, I'd like to debug further--though I can see where I need to add more checks for no data.

Either way, I'll leave this open as a reminder to improve the handling of cases like this.

**Comment by brentp** [comment]
thanks for the clear and complete report, BTW.

**Comment by robinandeer** [comment]
no problem - as a fellow developer I try to be as concise yet complete as possible :)

My targeted data is not anonymised so I'm not able to share that - I will look to see if we have some HapMap data or similar

I now get results for the WGS trio - fantastic!

Trying to interpret the results - I'll read up more but this seems odd; why are the sample correctly predicted as "male" marked as error?

![newplot](https://cloud.githubusercontent.com/assets/1220232/24049144/63d89028-0b2b-11e7-8437-5e6131302326.png)

**Comment by brentp** [comment]
well, normally the HET/HOM_ALT for males is < 0.1 and yours appear to be almost 2. That means you have almost 2X as many HET calls as HOM_ALT on the X and, as you know, HETs should be very rare on the X for males.

**Comment by robinandeer** [comment]
haha you saw the results - we reacted to the same thing but I figures I might be reading the results wrong.. We will look into this :)

**Comment by brentp** [comment]
closing this for now, but please re-open as needed.
