### ISSUE TITLE
IndexError: list index out of range (ped file is tab seperated and matplotlib is also updated).

### ISSUE THREAD

**Issue by shiva-g** [brentp/peddy#35]
2017-11-17 11:46:21 l-1-01 peddy.cli[97880] INFO Running Peddy version 0.3.2
Traceback (most recent call last):
  File "/home/ganesans/miniconda/envs/grinenv/bin/peddy", line 11, in <module>
    load_entry_point('peddy', 'console_scripts', 'peddy')()
  File "/home/ganesans/miniconda/envs/grinenv/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/ganesans/miniconda/envs/grinenv/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/ganesans/miniconda/envs/grinenv/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ganesans/miniconda/envs/grinenv/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/mnt/isilon/helbig_lab/software/peddy/peddy/cli.py", line 159, in peddy
    ped_obj = Ped(ped)
  File "/mnt/isilon/helbig_lab/software/peddy/peddy/peddy.py", line 441, in __init__
    self._parse(ped)
  File "/mnt/isilon/helbig_lab/software/peddy/peddy/peddy.py", line 460, in _parse
    sample = Sample.from_row(toks, header=self.header, warn=self.warn)
  File "/mnt/isilon/helbig_lab/software/peddy/peddy/peddy.py", line 262, in from_row
    return cls(row[0], row[1], row[2] or "-9", row[3] or "-9", row[4], row[5],
IndexError: list index out of range

**Comment by brentp** [comment]
sounds like you don't have 6 columns for all of the rows in your ped file.

**Comment by shiva-g** [comment]
Thanks!! Will look into it.

**Comment by brentp** [comment]
can you put the ped file here or email to me?

**Comment by shiva-g** [comment]
Fixed this! was using a different version of python!!! Thanks!
