### ISSUE TITLE
ped_check error -> ZeroDivisionError: float division

### ISSUE THREAD

**Issue by yocra3** [brentp/peddy#37]
Hi,

I am running peddy for the first time. I have managed to run peddy on the toy example of your repository but, when I apply it to my data, I have the following error:

```
[cruiz@isgws05 300]$  python -m peddy --plot --prefix cancer plink.vcf.gz ped.fam
2017-12-13 17:35:54 isgws05.isglobal.lan peddy.cli[64409] INFO Running Peddy version 0.3.1
2017-12-13 17:35:54 isgws05.isglobal.lan peddy.cli[64409] INFO ped_check
Traceback (most recent call last):
  File "/home/isglobal.lan/cruiz/anaconda/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/isglobal.lan/cruiz/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/isglobal.lan/cruiz/anaconda/lib/python2.7/site-packages/peddy/__main__.py", line 14, in <module>
    sys.exit(cli())
  File "/home/isglobal.lan/cruiz/anaconda/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/isglobal.lan/cruiz/anaconda/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/isglobal.lan/cruiz/anaconda/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/isglobal.lan/cruiz/anaconda/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/isglobal.lan/cruiz/anaconda/lib/python2.7/site-packages/peddy/cli.py", line 204, in peddy
    in ("ped_check", "het_check", "sex_check")]):
  File "/home/isglobal.lan/cruiz/anaconda/lib/python2.7/site-packages/peddy/cli.py", line 43, in run
    prefix=prefix, **kwargs)
  File "/home/isglobal.lan/cruiz/anaconda/lib/python2.7/site-packages/peddy/peddy.py", line 954, in ped_check
    min_depth=min_depth, each=each)
  File "cyvcf2/cyvcf2.pyx", line 52, in cyvcf2.cyvcf2.par_relatedness (cyvcf2/cyvcf2.c:4380)
  File "cyvcf2/cyvcf2.pyx", line 826, in cyvcf2.cyvcf2.VCF._relatedness_finish (cyvcf2/cyvcf2.c:20672)
ZeroDivisionError: float division
```

My dataset is a case-control study of prostate cancer so all individuals are males. Could this fact cause a problem?

Thank you
Carlos

**Comment by brentp** [comment]
could you update to the latest version of cyvcf2 (from pypi, not bioconda), re-run, and report the error?

**Comment by yocra3** [comment]
After updating cyvcf2, the previous problem was solved. 
Thank you
Carlos

**Comment by brentp** [comment]
Great! Thanks for following up.
