### ISSUE TITLE
No Hets found on numerous samples

### ISSUE THREAD

**Issue by AndrewSkelton** [brentp/peddy#50]
Hi, 

I get an error `peddy: no hets found for sample`, across numerous samples, however when looking in the VCF there appears to be het sites for these samples. 

Data:
WGS, passing sites only, called individually and merged using vcftools. Pedigree file and VCF look fine. Same hg19 reference used throughout. 

Log:
```
2018-09-17 10:32:39 job-FKPg89Q0KK87P2F23fF3f42K.dnanex.us peddy.cli[23825] INFO Running Peddy version 0.4.2
2018-09-17 10:32:40 job-FKPg89Q0KK87P2F23fF3f42K.dnanex.us peddy.cli[23825] INFO ped_check
#...numerous no hets found errors
2018-09-17 10:32:40 job-FKPg89Q0KK87P2F23fF3f42K.dnanex.us peddy.peddy[23825] INFO plotting
2018-09-17 10:32:41 job-FKPg89Q0KK87P2F23fF3f42K.dnanex.us peddy.cli[23825] INFO ran in 1.0 seconds
2018-09-17 10:32:41 job-FKPg89Q0KK87P2F23fF3f42K.dnanex.us peddy.cli[23825] INFO het_check
Traceback (most recent call last):
  File "/home/dnanexus/anaconda/bin/peddy", line 11, in <module>
    load_entry_point('peddy==0.4.2', 'console_scripts', 'peddy')()
  File "/home/dnanexus/anaconda/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/dnanexus/anaconda/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/dnanexus/anaconda/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dnanexus/anaconda/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/dnanexus/anaconda/lib/python2.7/site-packages/peddy/cli.py", line 207, in peddy
    in ("ped_check", "het_check", "sex_check")]):
  File "/home/dnanexus/anaconda/lib/python2.7/site-packages/peddy/cli.py", line 43, in run
    prefix=prefix, **kwargs)
  File "/home/dnanexus/anaconda/lib/python2.7/site-packages/peddy/peddy.py", line 866, in het_check
    sites, min_depth=min_depth)
  File "cyvcf2/cyvcf2.pyx", line 77, in cyvcf2.cyvcf2.par_het (cyvcf2/cyvcf2.c:5531)
  File "cyvcf2/cyvcf2.pyx", line 741, in cyvcf2.cyvcf2.VCF._finish_het (cyvcf2/cyvcf2.c:18532)
IndexError: index 0 is out of bounds for axis 0 with size 0
```

Understandably, I think the error comes from not being able to plot the het figures, if it can't find any hets. Is there anything I could try? The calls were generated by Dragen, but was passed through VCFtools, so I think the VCF schema is intact, I just wonder why it's not picking up the hets. Could it be because there's missing data in some samples from the merge?

**Comment by brentp** [comment]
> called individually and merged using vcftools.

this is the problem. you have no homozygous reference calls and that is causing an error. It's probably possible for peddy to support this use-case, but I for most things, a VCF like this is not going to be very useful and so it's not at the top of my list.

**Comment by AndrewSkelton** [comment]
That's completely fair.

**Comment by tatianaalmeida** [comment]
I had this same error and I called my vcf with GATK GenotypeGVCFs. Can you help me?

**Comment by brentp** [comment]
if your vcf does not have homozygous calls then it won't work in peddy. you could try running [somalier](https://github.com/brentp/somalier) directly on the bam files to get this information.
