### ISSUE TITLE
Library not loaded: @rpath/libdeflate.so

### ISSUE THREAD

**Issue by iq25** [brentp/peddy#64]
Hello. I created an environment with conda with python 2.7. Entered the command:
`pip install peddy`
And got an error:
`Traceback (most recent call last):
  File "/Users/nail/miniconda3/envs/peddy/bin/peddy", line 8, in <module>
    from peddy.__main__ import cli
  File "/Users/nail/miniconda3/envs/peddy/lib/python2.7/site-packages/peddy/__main__.py", line 3, in <module>
    from .cli import peddy as cli
  File "/Users/nail/miniconda3/envs/peddy/lib/python2.7/site-packages/peddy/cli.py", line 17, in <module>
    from cyvcf2 import VCF
  File "/Users/nail/miniconda3/envs/peddy/lib/python2.7/site-packages/cyvcf2/__init__.py", line 1, in <module>
    from .cyvcf2 import (VCF, Variant, Writer, r_ as r_unphased, par_relatedness,
ImportError: dlopen(/Users/nail/miniconda3/envs/peddy/lib/python2.7/site-packages/cyvcf2/cyvcf2.so, 2): Library not loaded: @rpath/libdeflate.so
  Referenced from: /Users/nail/miniconda3/envs/peddy/lib/libhts.2.dylib
  Reason: image not found`
What can I do with this issue?

**Comment by MiriamFF** [comment]
Hi, same here. I have installed peddy as a conda env with no issues 

```
$ conda create --name peddybox peddy
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate peddybox
#
# To deactivate an active environment, use
#
# $ conda deactivate 
```    

but when I run it 

`python -m peddy -p 4 --plot --sites hg38 --prefix FAM001 FAM001.trio.genotype.raw.vcf.gz FAM001.ped` 

I got same error as above

```
Traceback (most recent call last):
  File "/Users/miriam.fanjul/anaconda3/envs/peddybox/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/miriam.fanjul/anaconda3/envs/peddybox/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/miriam.fanjul/anaconda3/envs/peddybox/lib/python2.7/site-packages/peddy/__main__.py", line 3, in <module>
    from .cli import peddy as cli
  File "/Users/miriam.fanjul/anaconda3/envs/peddybox/lib/python2.7/site-packages/peddy/cli.py", line 17, in <module>
    from cyvcf2 import VCF
  File "/Users/miriam.fanjul/anaconda3/envs/peddybox/lib/python2.7/site-packages/cyvcf2/__init__.py", line 1, in <module>
    from .cyvcf2 import (VCF, Variant, Writer, r_ as r_unphased, par_relatedness,
ImportError: dlopen(/Users/miriam.fanjul/anaconda3/envs/peddybox/lib/python2.7/site-packages/cyvcf2/cyvcf2.so, 2): Library not loaded: @rpath/libdeflate.so
  Referenced from: /Users/miriam.fanjul/anaconda3/envs/peddybox/lib/libhts.2.dylib
  Reason: image not found
```

Any help will be greatly appreciated.
