### ISSUE TITLE
Running Ancestry Analysis on Samples with no Hets Found

### ISSUE THREAD

**Issue by angelussong** [brentp/peddy#69]
Hi @brentp!

I'm working on a project trying to run some ancestry analysis on single-cell RNAseq samples. I used monovar for the variant calling and then peddy for the ancestry calling. All my samples had no hets in them. When I ran peddy, I saw this error: 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/wynton/home/fhuanglab/hsong1/.conda/envs/py2/lib/python2.7/site-packages/peddy/peddy.py", line 866, in het_check
    sites, min_depth=min_depth)
  File "cyvcf2/cyvcf2.pyx", line 76, in cyvcf2.cyvcf2.par_het
  File "cyvcf2/cyvcf2.pyx", line 743, in cyvcf2.cyvcf2.VCF._finish_het
IndexError: index 0 is out of bounds for axis 0 with size 0

I'm wondering now if I could only run the ancestry analysis on these samples without the sex calling. Is that possible? 

Thanks very much!

**Comment by brentp** [comment]
yes, it's possible, but this doesn't appear to be failing on the sex check part.

**Comment by brentp** [comment]
ancestry uses PCA. a sample without hom-ref calls will cluster away from all other samples which have hom-ref, het and hom-alt, so this will not be useful.
I am trying to figure out a solution for this, but don't have one at this time.

**Comment by ruthbpaula** [comment]
Any updates on that? I am having the same issue.

**Comment by brentp** [comment]
@ruthbpaula your samples also have no hets? I don't think that peddy can work well in that case.
