### ISSUE TITLE
Error during pip install peddy

### ISSUE THREAD

**Issue by lyj95618** [brentp/peddy#83]
Hi, 

I tried to install peddy using `pip install peddy` and got the following error:
```
Collecting peddy
  Using cached https://files.pythonhosted.org/packages/04/80/9bac9a493cf82638d9da4d480de8ddfbfe1aeb501715f883de5790ea40a8/peddy-0.4.7.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /hpf/largeprojects/ccmbio/yliang/test_place/myenv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/localhd/tmp/pip-install-bss7m2ft/peddy/setup.py'"'"'; __file__='"'"'/localhd/tmp/pip-install-bss7m2ft/peddy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /localhd/tmp/pip-install-bss7m2ft/peddy/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/localhd/tmp/pip-install-bss7m2ft/peddy/setup.py", line 36, in <module>
        install_requires=get_requirements(),
      File "/localhd/tmp/pip-install-bss7m2ft/peddy/setup.py", line 8, in get_requirements
        with open("requirements.txt") as handle:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Thanks in advance!

Laur

**Comment by brentp** [comment]
Hi, can you try again? You should get v0.4.8 where I added `requirements.txt` to the `MANIFEST.in`.
