### ISSUE TITLE
gVCF input

### ISSUE THREAD

**Issue by zoeward-nz** [brentp/peddy#91]
Hi, 
I am trying to run PEDDY for the first time.
I have gVCF output from GATK exomesinglesample wdl 
The format of the vcf is like this:
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	F_001	F_002	F_003
chr1	11719	.	A	<NON_REF>	.	.	END=12377;AN=6;AC=0	GT:DP:GQ	0/0:0:0	0/0:0:0	0/0:0:0
chr1	12445	.	G	<NON_REF>	.	.	END=12972;AN=6;AC=0	GT:DP:GQ	0/0:3:0	0/0:5:0	0/0:4:0
chr1	13273	.	G	C,<NON_REF>	4974.06	.	AS_QUALapprox=|1522|0;AS_RAW_BaseQRankSum=|1.0,1|NaN;AS_RAW_MQ=112038.00|106888.00|0.00;AS_RAW_MQRankSum=|-0.7,1|NaN;AS_RAW_ReadPosRankSum=|-0.7,1|NaN;AS_SB_TABLE=40,44|40,29|0,0;AS_VarDP=84|69|0;BaseQRankSum=1.057;MQRankSum=-0.619;QUALapprox=1522;RAW_GT_COUNT=0,1,0;RAW_MQandDP=226479,157;ReadPosRankSum=-0.627;VarDP=153;DP=531;AN=6;AC=4,0	GT:AD:DP:GQ:PL:SB	0/1:84,69,0:153:99:1522,0,1821,1774,2028,3802:40,44,40,29	0/1:98,87,0:185:99:1853,0,2190,2146,2451,4597:53,45,46,41	1/1:2,184,0:186:99:4988,551,0,4988,551,4988:1,1,100,84
```

I 
When I run PEDDY I get:
```
2024-04-30 03:58:46 e4549ed3987b peddy.cli[1] INFO Running Peddy version 0.4.8
2024-04-30 03:58:46 e4549ed3987b peddy.cli[1] INFO ped_check
/opt/conda/lib/python3.7/site-packages/peddy/peddy.py:971: UserWarning: peddy: no hets found for sample F_001
  min_depth=min_depth, each=each)
/opt/conda/lib/python3.7/site-packages/peddy/peddy.py:971: UserWarning: peddy: no hets found for sample F_002
  min_depth=min_depth, each=each)
/opt/conda/lib/python3.7/site-packages/peddy/peddy.py:971: UserWarning: peddy: no hets found for sample F_003
  min_depth=min_depth, each=each)
2024-04-30 03:58:50 e4549ed3987b matplotlib.font_manager[1] INFO generated new fontManager
2024-04-30 03:58:51 e4549ed3987b peddy.peddy[1] INFO plotting
2024-04-30 03:58:52 e4549ed3987b peddy.cli[1] INFO ran in 5.7 seconds
2024-04-30 03:58:52 e4549ed3987b peddy.cli[1] INFO het_check
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.7/site-packages/peddy/__main__.py", line 14, in <module>
    sys.exit(cli())
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/peddy/cli.py", line 209, in peddy
    in ("ped_check", "het_check", "sex_check")]):
  File "/opt/conda/lib/python3.7/site-packages/peddy/cli.py", line 43, in run
    prefix=prefix, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/peddy/peddy.py", line 867, in het_check
    sites, min_depth=min_depth)
  File "cyvcf2/cyvcf2.pyx", line 81, in cyvcf2.cyvcf2.par_het
  File "cyvcf2/cyvcf2.pyx", line 809, in cyvcf2.cyvcf2.VCF._finish_het
IndexError: index 0 is out of bounds for axis 0 with size 0
```

Do I need to reformat the gVCF somehow to be able to run PEDDY?

**Comment by brentp** [comment]
Hi, peddy doesn't support gVCF, you could try [somalier](https://github.com/brentp/somalier).
